### ISSUE TITLE
Uppercase mistake in parameters for Deploy-Private-DNS-Zones policy set

### ISSUE THREAD

**Issue by feskehau** [Azure/Azure-Landing-Zones-Library#39]
Hi,

Three of the parameters in the Deploy-Private-DNS-Zones does not follow a consistent naming scheme. The names ends with ID in uppercase, in conflict with the rest of the parameters ending in Id.

Inconsistent parameters:
azureSiteRecoveryBackupPrivateDnsZoneID
azureSiteRecoveryBlobPrivateDnsZoneID
azureSiteRecoveryQueuePrivateDnsZoneID

How it probably should be:
azureIotCentralPrivateDnsZoneId
azureStorageTablePrivateDnsZoneId
azureStorageTableSecondaryPrivateDnsZoneId

Is there a reason for this? If not, I can submit a fix.

**Comment by matt-FFFFFF** [comment]
Thank you for pointing this out - at the moment these policies are synchronised from upstream in the [Azure/Enterprise-Scale](https://github.com/Azure/Enterprise-Scale) repo.

Please feel free to submit a fix there 😄
