### ISSUE TITLE
Decommissioned management group is missing

### ISSUE THREAD

**Issue by salimkapadia** [Azure/Azure-Landing-Zones-Library#40]
According to the [landing zone](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/tailoring-alz#what-is-a-landing-zone-archetype-in-azure-landing-zones) documentation, A decommissioned management group was supposed to be created but I don't see that in https://github.com/Azure/Azure-Landing-Zones-Library/blob/main/platform/alz/architecture_definitions/alz.alz_architecture_definition.json

**Comment by matt-FFFFFF** [comment]
fixed by #51
