### ISSUE TITLE
Defaults for VM Monitoring policy assignments are missing

### ISSUE THREAD

**Issue by JWilkinsonMB** [Azure/Azure-Landing-Zones-Library#57]
Defaults for the following policy assignments are missing from the library.

Deploy-VM-Monitoring
Deploy-VMSS-Monitoring
Deploy-vmHybr-Monitoring

There should one new default which will be used with the ~~change_tracking~~ vm_insights DCR created by the Management Resources AVM Module (One DCR for applies for all 3 policies, therefore one default)
https://github.com/Azure/terraform-azurerm-avm-ptn-alz-management?tab=readme-ov-file#-data_collection_rules

Additionally, the existing default ama_user_assigned_managed_identity_id should be extended so it applies to 

Deploy-VM-Monitoring
Deploy-VMSS-Monitoring

Note that this shouldn't apply to Deploy-vmHybr-Monitoring as UMI is not used with Arc

Originally raised in https://github.com/Azure/Azure-Landing-Zones-Library/issues/54 but raising separately for clarity rather than reopening

**Comment by matt-FFFFFF** [comment]
Thank you for this clarity @JWilkinsonMB - will make the changes

**Comment by matt-FFFFFF** [comment]
> There should one new default which will be used with the change_tracking DCR created by the Management Resources AVM Module (One DCR for applies for all 3 policies, therefore one default)

@JWilkinsonMB 

I think this should be the VM Insights DCR, do you not think?

**Comment by matt-FFFFFF** [comment]
Further to this: I believe I'm right

This is the built-in:  https://www.azadvertizer.net/azpolicyinitiativesadvertizer/924bfe3a-762f-40e7-86dd-5c8b95eb09e6.html

The dcrResourceId description links to this: https://learn.microsoft.com/en-us/azure/azure-monitor/vm/vminsights-migrate-deprecated-policies

**Comment by JWilkinsonMB** [comment]
My bad, yes it should. Shouldn't have copied and pasted from the other issue :)
