### ISSUE TITLE
Default for Defender SQL DCR rule is missing 

### ISSUE THREAD

**Issue by JWilkinsonMB** [Azure/Azure-Landing-Zones-Library#58]
The default for dcrResourceId is missing for the Deploy-MDFC-DefSQL-AMA policy assignment

https://github.com/Azure/Azure-Landing-Zones-Library/blob/35f5d01630d33a4200df9693e1ebf0ff860d52de/platform/alz/policy_assignments/deploy_mdfc_defsql_ama.alz_policy_assignment.json#L30-L32

There should one new default which will be used with the defender_sql DCR created by the Management Resources AVM Module 
https://github.com/Azure/terraform-azurerm-avm-ptn-alz-management?tab=readme-ov-file#-data_collection_rules

Originally raised in https://github.com/Azure/Azure-Landing-Zones-Library/issues/54 but raising separately for clarity rather than reopening

**Comment by matt-FFFFFF** [comment]
Thank you for this clarity @JWilkinsonMB - will make the changes
