### ISSUE TITLE
Default for change tracking DCR should be a single assignment rather than 3 separate ones

### ISSUE THREAD

**Issue by JWilkinsonMB** [Azure/Azure-Landing-Zones-Library#59]
3 separate defaults have been defined for the change tracking DCR:

https://github.com/Azure/Azure-Landing-Zones-Library/blob/35f5d01630d33a4200df9693e1ebf0ff860d52de/platform/alz/alz_policy_default_values.json#L33-L64

However, in the Management Resources AVM Module there is only a single change tracking policy DCR created which is intended to apply to all 3 policies.
https://github.com/Azure/terraform-azurerm-avm-ptn-alz-management?tab=readme-ov-file#-data_collection_rules

Outside of ALZ / AVM, the Azure docs themselves for deploying change tracking also instruct you to have a single DCR that you then reference in all 3 policies
https://learn.microsoft.com/en-us/azure/automation/change-tracking/enable-vms-monitoring-agent?tabs=singlevm%2Carcvm#enable-change-tracking-at-scale-using-azure-monitoring-agent

As there is only one DCR, it would be simpler and clearer if there was only one default. 

Originally raised in https://github.com/Azure/Azure-Landing-Zones-Library/issues/54 but raising separately for clarity rather than reopening

**Comment by matt-FFFFFF** [comment]
Thank you for this clarity @JWilkinsonMB - will make the changes
