### ISSUE TITLE
Policy assignment definitions deleted in platform/alz/2024.10.0

### ISSUE THREAD

**Issue by JWilkinsonMB** [Azure/Azure-Landing-Zones-Library#77]
It looks like there were a number of policy assignment definitions that were deleted as part of https://github.com/Azure/Azure-Landing-Zones-Library/pull/76, for example [platform/alz/policy_assignments/deny_resource_locations.alz_policy_assignment.json](https://github.com/Azure/Azure-Landing-Zones-Library/pull/76/files#diff-8f2a9f0f53f5e3e23f7dceeae33d78549e6d778d07a3d6ad83193f4b37c4ca4d)

I presume this is correct as I don't see them upstream, but just wanted to confirm that this was the intent, and that if we want to carry on using these assignments that we need to create / copy them into our own library?

Also curious how they got there to begin with as they don't ever seem to have been in the upstream definitions. Looks like it might have come across from CAF? If so is there an argument they should be included to help people migrating?

**Comment by matt-FFFFFF** [comment]
#RR

**Comment by jasperpostcn** [comment]
Hi @matt-FFFFFF, I am curious to know to which upstream repo you synced with. This specific example above, where with policies we set to which locations a resource can be deployed is being used in CAF a lot, so I am not sure why it would be removed here.

Is the "new way of working" (compared with the CAF supermodule) to add these assignments manually ?

**Comment by matt-FFFFFF** [comment]
Hi,

Upstream is Enterprise-Scale, at the moment we take policies from there.

There was some debt left over from migration from the old caf-enterprise-scale terraform module, so we took the opportunity to align for purposes of consistency.

If you need these older artefacts then it's simple to add them to your own library and use in conjunction.

**Comment by jasperpostcn** [comment]
Hi @matt-FFFFFF, oke that is clear. Do you have a link to the Enterprise-Scale "thingie" you are looking at ? 

Besides this, I am just curious how is decided what needs to be in there and what not. The Resource Location example from above seems to be a very default which is now removed from the baseline.

**Comment by matt-FFFFFF** [comment]
This one :) [Azure/Enterprise-Scale](https://github.com/Azure/Enterprise-Scale)

**Comment by matt-FFFFFF** [comment]
> Hi [@matt-FFFFFF](https://github.com/matt-FFFFFF), oke that is clear. Do you have a link to the Enterprise-Scale "thingie" you are looking at ?
> 
> Besides this, I am just curious how is decided what needs to be in there and what not. The Resource Location example from above seems to be a very default which is now removed from the baseline.

Resource location is a built-in, it's very easy to assign.
