### ISSUE TITLE
Default for Deploy-Diag-LogsCat is missing / needs renaming after upstream change

### ISSUE THREAD

**Issue by JWilkinsonMB** [Azure/Azure-Landing-Zones-Library#78]
The policy assignment name Deploy-Diag-Logs was recently updated to Deploy-Diag-Logs**Cat** upstream 
[eslzArm/managementGroupTemplates/policyAssignments/DINE-ResourceDiagnosticsPolicyAssignment.json](https://github.com/Azure/Enterprise-Scale/pull/1789/files#diff-8d6f732e7d3f38cb377e6b8bf2423e4258ee8fc64272cdadecfde94d81a860fb)

This was pulled into this library in https://github.com/Azure/Azure-Landing-Zones-Library/pull/76, so it has the new name:
https://github.com/Azure/Azure-Landing-Zones-Library/blob/e8d6d56eb1b954323ac34c6c4e22fe412a95bba0/platform/alz/policy_assignments/Deploy-Diag-LogsCat.alz_policy_assignment.json#L4

However, the default for `log_analytics_workspace_id` still has the old name:
https://github.com/Azure/Azure-Landing-Zones-Library/blob/e8d6d56eb1b954323ac34c6c4e22fe412a95bba0/platform/alz/alz_policy_default_values.json#L133-L138

Please can this be updated, and is there a way that these changes can be synchronised automatically in future?

**Comment by matt-FFFFFF** [comment]
Hi,

Thank you for catching this. We will work on automation to detect this issue in the future.

At the moment we are crafting these manually.

**Comment by matt-FFFFFF** [comment]
See additional check here: Azure/alzlib#182
