### ISSUE TITLE
[BUG] Migrating from alz/2024.10.1 to alz/2024.11.0 is failing

### ISSUE THREAD

**Issue by sriquen** [Azure/Azure-Landing-Zones-Library#88]
Hi,

When migrating to the alz/2024.11.0 version, I encounter an issue related to the new way of managing the private DNS zone ids.
The following capture illustrates this issue.

![Image](https://github.com/user-attachments/assets/f3532e5f-b69f-4d34-85d4-e7f5d93e577d)

May I ask you to check if something is wrong in this version?

**Comment by matt-FFFFFF** [comment]
Hi there!

Please update your [alz provider](https://github.com/Azure/terraform-provider-alz/releases/tag/v0.16.2) version as we've recently updated our tooling to correctly parse ARM functions.

`terraform init -upgrade` should do the trick!

If you like you can use the recently updated [0.10.0](https://github.com/Azure/terraform-azurerm-avm-ptn-alz/releases/tag/v0.10.0) release of the ALZ Terraform module. This comes with some new features to better support the deployment ordering

**Comment by sriquen** [comment]
Awesome, this works.
I've updated the alz provider to 0.16.2 (last version at this time), used the 0.10.0 release of the ALZ Terraform module, and the migration was successful.
Thank you
