### ISSUE TITLE
Reading data.alz_architecture takes a long time

### ISSUE THREAD

**Issue by carlzxc71** [Azure/Azure-Landing-Zones-Library#92]
Hello! 

We are using `data.alz_architecture.this` in our deployment to get access to and be able to reference the `policy_definitions` and `policy_set_definitions` and that is working well. 

 However, when running `terraform plan` it takes 90+ seconds to read the `data` source everytime. Since we are running this a lot and making frequent changes this time adds up and working with the data becomes very slow. 

Is there anything we can do to improve this? Can we cache the data somehow so that if no changes are made to the `provider` block or the `data` block we don't need to read everything everytime? 

Any insight here will be much appreciated, thank you! 

Sincerely, 
Carl

**Comment by matt-FFFFFF** [comment]
Azure/alzlib#168

Hi please see above. We are tracking this feature here.

I'm going to close this in favour of the above.
